import test from "node:test";
import assert from "node:assert/strict";
import { ROOM_TYPES, calculateAvailability, canCancelReservation, canTransition, isIsoDate, makeReservation, nightsBetween, normalizeEmail, validateBooking } from "./domain.js";

const validBooking = { guestName: "Ana López", guestEmail: "ANA@example.com", guestPhone: "+502 5555 1234", roomType: "patio", checkIn: "2026-04-11", checkOut: "2026-04-14", guests: 2 };
const clock = () => new Date("2026-04-10T12:00:00.000Z");

test("el catálogo define tres tipos con inventario y capacidad", () => { assert.equal(ROOM_TYPES.length, 3); assert.ok(ROOM_TYPES.every((room) => room.inventory > 0 && room.capacity > 0)); });
test("reconoce una fecha ISO real", () => assert.equal(isIsoDate("2026-04-10"), true));
test("rechaza una fecha de calendario imposible", () => assert.equal(isIsoDate("2026-02-29"), false));
test("rechaza texto en lugar de fecha", () => assert.equal(isIsoDate("mañana"), false));
test("rechaza el formato de fecha corto", () => assert.equal(isIsoDate("26-04-10"), false));
test("calcula noches por día de calendario", () => assert.equal(nightsBetween("2026-04-11", "2026-04-14"), 3));
test("normaliza correo para búsquedas consistentes", () => assert.equal(normalizeEmail("  ANA@Example.COM "), "ana@example.com"));
test("rechaza entradas de correo que no son texto", () => assert.equal(normalizeEmail(null), ""));
test("valida y normaliza una reserva completa", () => { const result = validateBooking(validBooking, clock()); assert.equal(result.valid, true); assert.equal(result.clean.guestEmail, "ana@example.com"); assert.equal(result.clean.total, 2055); });
test("recorta y compacta el nombre", () => assert.equal(validateBooking({ ...validBooking, guestName: "  Ana   López  " }, clock()).clean.guestName, "Ana López"));
test("rechaza nombre de un solo carácter", () => assert.equal(validateBooking({ ...validBooking, guestName: "A" }, clock()).valid, false));
test("rechaza etiquetas de HTML en el nombre", () => assert.equal(validateBooking({ ...validBooking, guestName: "<img src=x>" }, clock()).valid, false));
test("rechaza correo sin dominio", () => assert.equal(validateBooking({ ...validBooking, guestEmail: "ana@" }, clock()).valid, false));
test("acepta teléfono opcional", () => assert.equal(validateBooking({ ...validBooking, guestPhone: "" }, clock()).clean.guestPhone, null));
test("rechaza teléfono con letras", () => assert.equal(validateBooking({ ...validBooking, guestPhone: "abcde123456" }, clock()).valid, false));
test("rechaza un tipo de habitación desconocido", () => assert.equal(validateBooking({ ...validBooking, roomType: "penthouse" }, clock()).valid, false));
test("acepta la capacidad máxima de la habitación Patio", () => assert.equal(validateBooking({ ...validBooking, guests: 2 }, clock()).valid, true));
test("rechaza una persona sobre la capacidad del Patio", () => assert.equal(validateBooking({ ...validBooking, guests: 3 }, clock()).valid, false));
test("acepta salida al día siguiente", () => assert.equal(validateBooking({ ...validBooking, checkOut: "2026-04-12" }, clock()).clean.nights, 1));
test("rechaza salida anterior a la llegada", () => assert.equal(validateBooking({ ...validBooking, checkOut: "2026-04-11" }, clock()).valid, false));
test("rechaza estancias mayores de 30 noches", () => assert.equal(validateBooking({ ...validBooking, checkOut: "2026-05-12" }, clock()).valid, false));
test("rechaza llegada pasada", () => assert.equal(validateBooking({ ...validBooking, checkIn: "2026-04-09" }, clock()).valid, false));
test("rechaza reservas a más de 365 días", () => assert.equal(validateBooking({ ...validBooking, checkIn: "2027-05-01", checkOut: "2027-05-02" }, clock()).valid, false));
test("rechaza un grupo con huéspedes fraccionarios", () => assert.equal(validateBooking({ ...validBooking, guests: 1.5 }, clock()).valid, false));
test("disponibilidad descuenta reservas con cruce de fechas", () => { const room = ROOM_TYPES[0]; const active = [{ status: "CONFIRMADA", checkIn: "2026-04-10", checkOut: "2026-04-12" }]; assert.equal(calculateAvailability(room, active, "2026-04-11", "2026-04-13").available, 4); });
test("una salida el día de llegada de la nueva reserva no se traslapa", () => { const room = ROOM_TYPES[0]; const active = [{ status: "CONFIRMADA", checkIn: "2026-04-09", checkOut: "2026-04-11" }]; assert.equal(calculateAvailability(room, active, "2026-04-11", "2026-04-13").available, room.inventory); });
test("las canceladas dejan libre el inventario", () => { const active = [{ status: "CANCELADA", checkIn: "2026-04-10", checkOut: "2026-04-12" }]; assert.equal(calculateAvailability(ROOM_TYPES[0], active, "2026-04-11", "2026-04-13").available, 5); });
test("la habitación familiar es adecuada para cinco huéspedes", () => assert.equal(calculateAvailability(ROOM_TYPES[2], [], "2026-04-11", "2026-04-13", 5).suitable, true));
test("usa reloj de prueba al comprobar reserva cancelable", () => { const reservation = { status: "CONFIRMADA", checkIn: "2026-04-14" }; assert.equal(canCancelReservation(reservation, clock()), true); });
test("rechaza cancelación dentro de la ventana de 48 horas", () => { const reservation = { status: "CONFIRMADA", checkIn: "2026-04-11" }; assert.equal(canCancelReservation(reservation, clock()), false); });
test("una reserva cancelada es un estado terminal", () => assert.equal(canCancelReservation({ status: "CANCELADA", checkIn: "2026-04-20" }, clock()), false));
test("solo permite la transición de confirmada a cancelada", () => assert.equal(canTransition("CONFIRMADA", "CANCELADA"), true));
test("no permite reactivar una cancelación", () => assert.equal(canTransition("CANCELADA", "CONFIRMADA"), false));
test("rechaza transición desconocida", () => assert.equal(canTransition("CONFIRMADA", "BORRADOR"), false));
test("un stub de identificador y código da resultados repetibles", () => { const result = makeReservation(validBooking, { now: clock, id: () => "prueba-id", code: () => "ECO8K2PM" }); assert.equal(result.ok, true); assert.equal(result.reservation.id, "prueba-id"); assert.equal(result.reservation.confirmationCode, "ECO8K2PM"); });
test("devuelve errores antes de intentar persistir una reserva inválida", () => { const result = makeReservation({ ...validBooking, guests: 9 }, { now: clock, id: () => { throw new Error("No debe ejecutarse"); } }); assert.equal(result.ok, false); });
