export const attractions = [
  { name: "Arco de Santa Catalina", area: "ANTIGUA", type: "Arquitectura", description: "El arco amarillo es uno de los símbolos más reconocidos de la ciudad. Recorre la Calle del Arco temprano, cuando el centro está más tranquilo.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Arco+de+Santa+Catalina+Antigua+Guatemala" },
  { name: "Parque Central", area: "ANTIGUA", type: "Punto de encuentro", description: "Un buen lugar para orientarse entre portales, fachadas históricas y la vida cotidiana del centro.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Parque+Central+Antigua+Guatemala" },
  { name: "Iglesia de La Merced", area: "ANTIGUA", type: "Patrimonio", description: "Su fachada barroca destaca entre las iglesias de la ciudad. El conjunto permite apreciar la escala de la arquitectura religiosa antigüeña.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Iglesia+La+Merced+Antigua+Guatemala" },
  { name: "Convento de Capuchinas", area: "ANTIGUA", type: "Historia", description: "Sus patios y espacios circulares muestran otra faceta de la vida conventual en la antigua capital.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Convento+de+Capuchinas+Antigua+Guatemala" },
  { name: "Catedral de San José", area: "ANTIGUA", type: "Patrimonio", description: "Frente al parque central, el templo y las ruinas cuentan distintas etapas de la historia de la ciudad.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Catedral+de+San+Jos%C3%A9+Antigua+Guatemala" },
  { name: "San Francisco el Grande", area: "ANTIGUA", type: "Historia", description: "Visita el conjunto franciscano y conoce la historia de Santo Hermano Pedro, ligada a este lugar.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Iglesia+San+Francisco+el+Grande+Antigua+Guatemala" },
  { name: "Cerro de la Cruz", area: "ANTIGUA", type: "Mirador", description: "Un mirador para contemplar los tejados del centro y los volcanes. Consulta las condiciones de acceso antes de subir.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Cerro+de+la+Cruz+Antigua+Guatemala" },
  { name: "San Juan del Obispo", area: "ALREDEDORES", type: "Pueblo cercano", description: "Un recorrido por el convento, la iglesia y el parque del pueblo ayuda a descubrir la vida de los alrededores.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=San+Juan+del+Obispo+Sacatep%C3%A9quez" },
  { name: "San Antonio Aguas Calientes", area: "ALREDEDORES", type: "Artesanía", description: "Conoce el trabajo textil y los oficios locales en una comunidad cercana a Antigua.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=San+Antonio+Aguas+Calientes+Sacatep%C3%A9quez" },
  { name: "Ciudad Vieja", area: "ALREDEDORES", type: "Historia", description: "La antigua sede de Santiago de Guatemala invita a ampliar el recorrido por la historia colonial de la región.", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Ciudad+Vieja+Sacatep%C3%A9quez" },
];
